### ISSUE TITLE
Does component get rendered before async state is resolved?

### ISSUE THREAD

**Issue by cramatt** [KELiON/redux-async-initial-state#14]
It seems that in use components get rendered initially with an empty store, then re-rendered shortly there after when then async request resolves. Is this the desired behavior? 

If so, how might one account for a situation where they don't want the component to be rendered UNTIL the async request resolves?

**Comment by KELiON** [comment]
@cramatt in [innerReducer](https://github.com/KELiON/redux-async-initial-state#reducer) you have `loaded` and `loading` flags. So, you just have to hide your component while `loaded` is false, as I see it should be something like this: 

```
import React from 'react';
import { connect } from 'react-redux';

@connect(state => ({
  loaded: state.asyncInitialState.loaded,
}))
class MyComponent extends React.Component {
  render() {
    if (!this.props.loaded) {
      return <div>Waiting for data...</div>
    }
    return ...; // your component is here
  }
}
````

**Comment by cramatt** [comment]
Nice, this pattern works well!
