### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by JiDai** [KELiON/redux-async-initial-state#2]
Hi, I tried to implement this lib in an empty project with react router, but I did not succeed is there an example anywhere ? (with or without router).
Thanks

**Comment by KELiON** [comment]
@JiDai Hi! Can you give me more details, please, what problems did you have with setup? All you need to do is to add middleware to your store builder, as described [here](https://github.com/KELiON/redux-async-initial-state#usage).

**Comment by JiDai** [comment]
Hi,
I don't understand how the fetched data is injected in the store.
I have made a little project to test the case : https://github.com/JiDai/redux-async-initial-state-example

At the line :https://github.com/JiDai/redux-async-initial-state-example/blob/master/src/main.js#L27 : how I can pass the data to the store ?

For now I have the following error : 
`Unexpected keys "id", "name", "username", "email", "address", "phone", "website", "company" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "asyncInitialState". Unexpected keys will be ignored.`

Thanks

**Comment by KELiON** [comment]
@JiDai I've created a [pull request](https://github.com/JiDai/redux-async-initial-state-example/pull/1) in your example with explanation and fix. Let me know if you need something else!
