### ISSUE TITLE
Actions are dispatched before initial state is loaded

### ISSUE THREAD

**Issue by borNfreee** [KELiON/redux-async-initial-state#9]
Hi,

I have a container component that is connected to redux via `connect()` function and it has `componentDidMount()` function that dispatches an action `XXX`.

When I load the page, this action `XXX` is dispatched BEFORE `redux-async-initial-state/STATE_LOADING_DONE`.

Is it a correct behavior? Should any action be dispatched (and container's `render()` method called) before initial state is loaded?

**Comment by KELiON** [comment]
@borNfreee sure it is correct behaviour! This package doesn't block any renders. In your example flow is:

* create store
* request async initial state
* render your component 
* request async initial state finished

When the last step happens you can re-render your component or do some other action. I.e. you can show preloader (like in [example](https://github.com/KELiON/redux-async-initial-state#reducer)).

As a solution for you case, you can wrap your container with some wrapper, that renders your Container only when state is loaded, so `componentDidMount()` will be called only when your have your initial state in redux store

```
import YourContainer from '..'


@connect(state => ({
  loading: state.asyncInitialState.loading,
  loaded: state.asyncInitialState.loaded,
  error: state.asyncInitialState.error,
}))
const Wrapper = ({ loading, loader, error}) => {
  if (loading) {
    return <SomeSpinner />
  }
  if (error) {
    return <SomeErrorComponent />
  }
  return <YourContainer />
}
```

Another solution (that I like less) is to call redux action not in `componentDidMount`, but in `componentWillReceiveProps`, so you can check that state is ready.

**Comment by borNfreee** [comment]
thank you!

**Comment by borNfreee** [comment]
@KELiON I have additional question related to this topic.

As I understand the purpose of this middleware is to load **initial** state asynchroniously, but it seems like it does not block other actions to be dispatched (and it means all reducers are triggered while initial state is not yet loaded).

So the quesition is: what is the benefit to load **initial** state while all other actions can be dispatched and reducers already returned theirs `initiale` sub-tree states?

Isn't it the same like dispatching e.g. `REQUEST_SOMETHING` action on `componentDidMount()` method? I can't understand the goal of this middleware :(

In my case I wanted to load data from the server that is **required** for other reducers. They can't work without this *initial* data. But this plugin does not allow it.

Did I miss something?

Thanks

**Comment by KELiON** [comment]
redux is super-simple library, without any magic. That is I wanted to continue in this packages: no magic. I think it is possible to block actions dispatch, until the state is loaded and dispatch them only after it, but it adds some hidden functionality for developer, who uses it. Instead, this library provides simple wrapper, that allows to get initial state from some Promise.

> Isn't it the same like dispatching e.g. REQUEST_SOMETHING action on componentDidMount() method?

Kinda, but it doesn't depend on react and on your component's lifecycle. You just define promise as a way to get your initial state – after that you can do whatever you want: subscribe to `redux-async-initial-state/STATE_LOADING_DONE` action, conditionally render your component/container, etc.

**Comment by borNfreee** [comment]
@KELiON I wanted to say that *initial* means that this is required to make application valid to start the work.

But with current approach it's not true. Let's have an example:

```js

// application redux state:
{
    user: {isAdmin: true/false, isModerator: true/false},
    dashboard: {
        products: [{id: 1}, ...],
        someDataDependentOnUserState: {} // differs for admin and moderator and EDITABLE
    }
}
```

Two reducers: `user` and `dashboard`.
Imagine there are actions `PRODUCTS_REQUEST`, `PRODUCTS_SUCCESS`.
User is loaded by this middleware as *initial async state*.

```js
// dashboardReducer.js

function dashboardReducer(state = {}, action) {
    // !!! here we have a problem because user initial state is not yet loaded and we don't know what is the default value for the state. It must depend on isAdmin/isModerator flags, but they are still not fetched
}
```

So the whole list of dispatched events are:

1. `@init` by redux
2. `redux-async-initial-state/STATE_LOADING_START`
3. `PRODUCTS_REQUEST`
4. `PRODUCTS_SUCCESS`
5. `redux-async-initial-state/STATE_LOADING_DONE`

Starting even from the first dispatched event, the `dashboardReducer` reducer is executed and since we don't have `user` data in the state, we can't build `dashboard.someDataDependentOnUserState` value.

I hope you see my point ;). This is pretty simple - there can be situation when one tree of the state depends on really *initial data* that must be present before continue to work. And I don't understand how to accomplish this with your middleware.

**Comment by KELiON** [comment]
@borNfreee sorry, but I don't understand your problem, because you can, i.e. have `null` initially in `dashboard.someDataDependentOnUserState`, but build it depend on `user` only after state is ready.

Furthermore, it looks like if you want to have dependency in one branch of state on another one, probably you don't need to store this data in state and it is better to build it in `mapStateToProps` or even use some library, like `reselect`.
